"""Initial migration

Revision ID: 8ecc486c1fce
Revises: 
Create Date: 2026-04-10 12:44:50.739034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ecc486c1fce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_sqlx_migrations')
    op.drop_column('developers', 'created_at')
    op.alter_column('package_versions', 'version',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('package_versions', 'checksum',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint(op.f('package_versions_package_id_version_key'), 'package_versions', type_='unique')
    op.drop_constraint(op.f('package_versions_package_id_fkey'), 'package_versions', type_='foreignkey')
    op.create_foreign_key(None, 'package_versions', 'packages', ['package_id'], ['id'], ondelete='CASCADE')
    op.drop_column('package_versions', 'created_at')
    op.drop_constraint(op.f('packages_developer_id_fkey'), 'packages', type_='foreignkey')
    op.create_foreign_key(None, 'packages', 'developers', ['developer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('packages', 'created_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('packages', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'packages', type_='foreignkey')
    op.create_foreign_key(op.f('packages_developer_id_fkey'), 'packages', 'developers', ['developer_id'], ['id'])
    op.add_column('package_versions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'package_versions', type_='foreignkey')
    op.create_foreign_key(op.f('package_versions_package_id_fkey'), 'package_versions', 'packages', ['package_id'], ['id'])
    op.create_unique_constraint(op.f('package_versions_package_id_version_key'), 'package_versions', ['package_id', 'version'], postgresql_nulls_not_distinct=False)
    op.alter_column('package_versions', 'checksum',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('package_versions', 'version',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('developers', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.create_table('_sqlx_migrations',
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('installed_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('checksum', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('execution_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version', name=op.f('_sqlx_migrations_pkey'))
    )
    # ### end Alembic commands ###
