"""store package bytes in database

Revision ID: eb60bb1a7502
Revises: 60c98a553be3
Create Date: 2026-04-12 15:31:23.107363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb60bb1a7502'
down_revision: Union[str, Sequence[str], None] = '60c98a553be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_versions', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    op.alter_column('package_versions', 'file_path',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('package_versions', 'file_path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('package_versions', 'file_data')
    # ### end Alembic commands ###
