name: Release CLI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    name: Build and Release CLI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: vget
            asset_name: vget-linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: vget
            asset_name: vget-macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            binary_name: vget
            asset_name: vget-macos-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: vget.exe
            asset_name: vget-windows-amd64.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build CLI Binary
        run: cargo build --release -p cli --target ${{ matrix.target }}

      - name: Rename Binary
        run: |
          mv target/${{ matrix.target }}/release/${{ matrix.binary_name }} ./${{ matrix.asset_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}